{{- range $service := .Values.services }}
{{- if $service.daemonset.enabled }}
{{- else }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}-deployment
  namespace: {{ $.Values.environment }}
  labels:
    projectname: dockercoins
    environment: {{ $.Values.environment }}
    servicename: {{ $service.name }}
spec:
  replicas: {{ $service.replicaCount }}
  selector:
    matchLabels:
      app: {{ $service.name | quote }}
  template:
    metadata:
      labels:
        app: {{ $service.name | quote }}
    spec:
      containers:
        - name: {{ $service.name }}
          image: {{ $.Values.registry }}/{{ $service.image.repository }}:{{ $service.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ $service.port }}
          {{- if $service.healthcheck }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ $service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ $service.port }}
          {{- end }}
          env:
            - name: PROJECT_NAME
              value: dockercoins
            - name: ENVIRONMENT
              value: {{ $.Values.environment }}
            - name: SERVICE_NAME
              value: {{ $service.name }}
{{- end }}
{{- end }}
