# NODEPORT=$(kubectl get svc/registry -o json | jq .spec.ports[0].nodePort)
# REGISTRY=127.0.0.1:$NODEPORT
# curl $REGISTRY/v2/_catalog
# cd /vagrant/apps/dockercoins
# export REGISTRY_SLASH=$REGISTRY/
# export COLON_TAG=:v0.1
# docker-compose -f docker-compose.images.yml build
# docker-compose -f docker-compose.images.yml push
#
# kubectl create namespace dev
# kubectl create namespace uat
# kubectl create namespace prod
#
#######dev
# kubectl run redis --image=redis --namespace dev
# kubectl expose deployment redis --port 6379 --namespace dev
# helm upgrade --install dev-hasher dockercoins-chart/ --set environment=dev --set service.enabled=true --set service.name=hasher --set image.repository=127.0.0.1:31601/hasher --set image.tag=v0.1 --set daemonset.enabled=false --set ingress.enabled=false
# helm upgrade --install dev-worker dockercoins-chart/ --set environment=dev --set service.enabled=false --set service.name=worker --set image.repository=127.0.0.1:31601/worker --set image.tag=v0.2 --set daemonset.enabled=false --set ingress.enabled=false
# helm upgrade --install dev-rng dockercoins-chart/ --set environment=dev --set service.enabled=true --set service.name=rng --set image.repository=127.0.0.1:31601/rng --set image.tag=v0.1 --set daemonset.enabled=true --set ingress.enabled=false
# helm upgrade --install dev-webui dockercoins-chart/ --set environment=dev --set service.enabled=true --set service.name=webui --set image.repository=127.0.0.1:31601/webui --set image.tag=v0.2 --set daemonset.enabled=false --set ingress.enabled=true --set ingress.hosts=dev-webui.192.168.33.111.nip.io
# kubectl get all -n dev
#######uat
# kubectl run redis --image=redis --namespace uat
# kubectl expose deployment redis --port 6379 --namespace uat
# helm upgrade --install uat-hasher dockercoins-chart/ --set environment=uat --set service.enabled=true --set service.name=hasher --set service.healthcheck=true --set image.repository=127.0.0.1:31601/hasher --set image.tag=v0.1 --set daemonset.enabled=false --set ingress.enabled=false
# helm upgrade --install uat-worker dockercoins-chart/ --set environment=uat --set service.enabled=false --set service.name=worker --set service.healthcheck=false --set image.repository=127.0.0.1:31601/worker --set image.tag=v0.2 --set daemonset.enabled=false --set ingress.enabled=false
# helm upgrade --install uat-rng dockercoins-chart/ --set environment=uat --set service.enabled=true --set service.name=rng --set service.healthcheck=true --set image.repository=127.0.0.1:31601/rng --set image.tag=v0.1 --set daemonset.enabled=true --set ingress.enabled=false
# helm upgrade --install uat-webui dockercoins-chart/ --set environment=uat --set service.enabled=true --set service.name=webui --set service.healthcheck=true --set image.repository=127.0.0.1:31601/webui --set image.tag=v0.2 --set daemonset.enabled=false --set ingress.enabled=true --set ingress.hosts=uat-webui.192.168.33.111.nip.io
# kubectl get all -n uat
#######prod
# helm upgrade --install dockercoins dockercoins-chart-prod/
# kubectl get all -n prod
#######debug
# helm delete --purge uat-worker
# helm template dockercoins-chart/ -x templates/deployment.yaml --set environment=uat --set service.enabled=true --set service.name=webui --set service.healthcheck=true --set image.repository=127.0.0.1:31601/webui --set image.tag=v0.2 --set daemonset.enabled=false --set ingress.enabled=true --set ingress.hosts=uat-webui.192.168.33.111.nip.io
environment: prod

registry: 127.0.0.1:31601

services:
  - name: hasher
    port: 80
    targetPort: 80
    healthcheck: true
    replicaCount: 1
    service:
      enable: true
      type: ClusterIP
    daemonset:
      enabled: false
    image:
      repository: hasher
      tag: v0.1
    ingress:
      enabled: false
  - name: worker
    port: 80
    targetPort: 80
    healthcheck: false
    replicaCount: 1
    service:
      enable: false
      type: ClusterIP
    daemonset:
      enabled: false
    image:
      repository: worker
      tag: v0.2
    ingress:
      enabled: false
  - name: rng
    port: 80
    targetPort: 80
    healthcheck: true
    replicaCount: 1
    service:
      enable: true
      type: ClusterIP
    daemonset:
      enabled: true
    image:
      repository: rng
      tag: v0.1
    ingress:
      enabled: false
  - name: webui
    port: 80
    targetPort: 80
    healthcheck: true
    replicaCount: 1
    service:
      enable: true
      type: ClusterIP
    daemonset:
      enabled: false
    image:
      repository: webui
      tag: v0.2
    ingress:
      enabled: true
      hosts: webui.192.168.33.111.nip.io
