{{- if .Values.daemonset.enabled -}}
{{- else }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}-deployment
  namespace: {{ .Values.environment }}
  labels:
    projectname: dockercoins
    environment: {{ .Values.environment }}
    servicename: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name | quote }}
    spec:
      containers:
        - name: {{ .Values.service.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          {{- if .Values.service.healthcheck }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ $.Values.service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ $.Values.service.port }}
          {{- end }}
          env:
            - name: PROJECT_NAME
              value: dockercoins
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
            - name: SERVICE_NAME
              value: {{ .Values.service.name }}
{{- end }}
